DROP TABLE COMANDABILEDA;
DROP TABLE ESPERTOIN;
DROP TABLE MODELLO;
DROP TABLE SOCIO;
DROP TABLE TESTESEGUITI;
DROP TABLE PERSONALEMARITTIMO;
DROP TABLE TECNICO;
DROP TABLE IMBARCAZIONE;
DROP TABLE TESTIMBARCAZIONE;

DROP TYPE COMANDABILEDATYPE;
DROP TYPE TESTESEGUITITYPE;
DROP TYPE ESPERTOINTYPE;
DROP TYPE SOCIOTYPE;
DROP TYPE TECNICOTYPE;
DROP TYPE PERSONALEMARITTIMOTYPE;
DROP TYPE IMBARCAZIONETYPE;
DROP TYPE MODELLOTYPE;
DROP TYPE DIPENDENTETYPE;
DROP TYPE TESTIMBARCAZIONETYPE;

DROP SEQUENCE testeseguti_sequence;